package com.runners.app.global.exception;

public enum ErrorCode {
    VALIDATION_FAILED,

    // User / profile
    USER_ID_INVALID,
    USER_NOT_FOUND,
    NICKNAME_DUPLICATED,
    NICKNAME_INVALID_FORMAT,
    NICKNAME_TOO_SHORT,
    NICKNAME_TOO_LONG,
    NICKNAME_REQUIRED,
    INTRO_TOO_LONG,
    PROFILE_IMAGE_FILES_COUNT_INVALID,
    PROFILE_IMAGE_KEY_REQUIRED,
    PROFILE_IMAGE_KEY_INVALID,
    TOTAL_DISTANCE_REQUIRED,
    TOTAL_DISTANCE_OUT_OF_RANGE,
    TOTAL_DURATION_REQUIRED,
    TOTAL_DURATION_OUT_OF_RANGE,
    RUN_COUNT_REQUIRED,
    RUN_COUNT_OUT_OF_RANGE,

    // Community
    TITLE_REQUIRED,
    TITLE_TOO_LONG,
    CONTENT_REQUIRED,
    IMAGE_TOO_MANY,
    IMAGE_KEY_REQUIRED,
    IMAGE_KEY_TOO_LONG,
    POST_NOT_FOUND,
    COMMENT_NOT_FOUND,
    PARENT_COMMENT_NOT_FOUND,
    INVALID_ID,
    INVALID_CURSOR,
    COMMENT_NOT_IN_POST,
    NO_PERMISSION,
    QUERY_REQUIRED,
    INVALID_FIELD,

    // Auth / security
    UNAUTHORIZED,
    INVALID_TOKEN,
    FORBIDDEN,
    REQUEST_BODY_NOT_ALLOWED,
    REFRESH_TOKEN_MISSING,
    REFRESH_TOKEN_INVALID,

    // Generic
    BAD_REQUEST,
    NOT_FOUND,
    CONFLICT,
    INTERNAL_ERROR,

    // Upload / S3
    UPLOAD_INVALID_KEY,
    UPLOAD_FILES_REQUIRED,
    UPLOAD_TOO_MANY_FILES,
    UPLOAD_FILE_REQUIRED,
    UPLOAD_FILE_NAME_TOO_LONG,
    UPLOAD_CONTENT_TYPE_REQUIRED,
    UPLOAD_CONTENT_TYPE_NOT_ALLOWED,
    UPLOAD_CONTENT_TYPE_TOO_LONG,
    UPLOAD_CONTENT_LENGTH_INVALID,
    UPLOAD_FILE_TOO_LARGE,
    UPLOAD_S3_CONFIG_INVALID,
    UPLOAD_S3_DELETE_FAILED,
}
